FMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from FestivalReservations import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fest/', include('FestivalReservations.urls')),
    path('', views.home, name="home")
] 

FestivalReservations/urls.py
from django.urls import path
from .views import (ReservationCreate, userPage, registerPage, loginPage, logoutUser, FestivalList,
                   InterpretList, FestivalDelete, InterpretCreate, InterpretDelete,
                   InterpretUpdate, FestivalDetail, InterpretDetail, FestivalCreate,
                   FestivalUpdate, MyReservations, ReservationsAdmin, ReservationEdit, AddShow,
                   UserAdmin, UserEditAdmin, ChangePasswordAdmin, ChangePassword, UserEdit, AddUser)
from .views import home
from django.conf import settings
from django.conf.urls.static import static

app_name='FestivalReservations'

urlpatterns=[
	path('FestivalList/', FestivalList.as_view(), name='FestivalList'),
	path('FestivalList/<slug:slug>', FestivalList.as_view(), name='FestivalList'),
	path('FestivalCreate/', FestivalCreate.as_view(), name='FestivalCreate'),
	path('FestivalDetail/<int:pk>', FestivalDetail.as_view(), name='FestivalDetail' ),
    path('FestivalDelete/<int:pk>', FestivalDelete.as_view(), name='FestivalDelete'),
    path('FestivalUpdate/<int:pk>', FestivalUpdate.as_view(), name='FestivalUpdate'),
	path('InterpretList/', InterpretList.as_view(), name='InterpretList'),
    path('InterpretCreate/', InterpretCreate.as_view(), name='InterpretCreate'),
	path('InterpretDetail/<int:pk>', InterpretDetail.as_view(), name='InterpretDetail'),
    path('InterpretDelete/<int:pk>', InterpretDelete.as_view(), name='InterpretDelete'),
    path('InterpretUpdate/<int:pk>', InterpretUpdate.as_view(), name='InterpretUpdate'),
    path('register/<email>/', registerPage, name="register"),
    path('register/', registerPage, name="register"),
    path('login/', loginPage, name="login"),
    path('logout/', logoutUser, name="logout"),
    path('user/', userPage, name="user-page"),
    path('reservation/<int:pk>', ReservationCreate.as_view(), name="reservation-page"),
    path('MyReservations/', MyReservations, name="MyReservations"),
    path('ReservationsAdmin/', ReservationsAdmin, name="ReservationsAdmin"),
    path('ReservationsAdmin/<int:pk>', ReservationsAdmin, name="ReservationsAdmin"),
    path('ReservationEdit/<int:pk>', ReservationEdit, name="ReservationEdit"),
    path('AddShow/<int:pk>', AddShow.as_view(), name='AddShow'),
    path('UserAdmin/', UserAdmin, name='UserAdmin'),
    path('UserAdmin/<int:pk>', UserAdmin, name='UserAdmin'),
    path('UserEditAdmin/<int:pk>', UserEditAdmin, name='UserEditAdmin'),
    path('ChangePasswordAdmin/<int:pk>', ChangePasswordAdmin, name='ChangePasswordAdmin'),
    path('ChangePassword/', ChangePassword, name='ChangePassword'),
    path('UserEdit/', UserEdit, name='UserEdit'),
    path('AddUser/', AddUser, name='AddUser'),
    path('', home, name="home")
]
urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FestivalReservations/models.py
from django.db import models
from jsonfield import JSONField
from django.conf import settings
# Create your models here.
class Festival(models.Model):

	FestivalBrand = models.CharField(max_length=30, verbose_name= ("Jméno"))
	Place = models.CharField(max_length=400, verbose_name= ("Místo"))
	Genre = models.CharField(max_length=30, verbose_name= ("Žánr"))
	Start = models.DateField(default="2020-01-01", verbose_name= ("Začátek"))
	End = models.DateField(default="2020-02-01", verbose_name= ("Konec"))
	PriceForTicket = models.IntegerField(verbose_name= ("Cena za lístek"))
	Capacity = models.IntegerField(verbose_name= ("Kapacita"))
	photoLogo = models.ImageField(upload_to="./FestivalReservations/static/images/festival", null=True, blank=True, verbose_name= ("Fotografie"))

	def __str__(self):
		return f'{self.FestivalBrand}'


class Interpret(models.Model):
	Name = models.CharField(max_length=30)
	Members = models.CharField(max_length=100)
	photoLogo = models.ImageField(upload_to="./FestivalReservations/static/images/interpret", null=True, blank=True)
	Rating = models.IntegerField()
	Genre = models.CharField(max_length=30)

	def __str__(self):
		return f'{self.Name}   ({self.Genre})'
	
	
class Reservation(models.Model):
	User = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name = 'Uživatel',related_name='reservations', null=True) 
	Festival = models.ForeignKey(Festival, on_delete=models.CASCADE)
	Tickets = models.IntegerField()
	Paid = models.BooleanField(default=False, null=True)


class Stage(models.Model):
	Label = models.IntegerField()
	Festival = models.ForeignKey(Festival, on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.Label}'


class Show(models.Model):
	Interpret = models.ForeignKey(Interpret, on_delete=models.CASCADE)
	Stage = models.ForeignKey(Stage, on_delete=models.CASCADE)
	Date = models.DateField()
	Start = models.TimeField()
	End = models.TimeField()

FestivalReservations/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse
from .models import Festival, Interpret, Reservation, Show, Stage
from .forms import (FestivalForm, InterpretForm, CreateUserForm, ReservationForm,
                    ReservationEditForm, ChangePasswordAdminForm, UserEditAdminForm,
                    UserEditForm, UserPasswordForm, ShowForm, AddUserForm)
from vanilla import ListView, DetailView, CreateView, TemplateView, UpdateView
from django.views.generic.edit import DeleteView 
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from .decorators import unauthenticated_user, allowed_users
from django.utils.decorators import method_decorator
# Create your views here.

def home(request):
    return render(request, "home.html", {})

class FestivalList(ListView):
    model = Festival

@method_decorator(allowed_users(allowed_roles=['admin', 'organizer']), name='dispatch')
class FestivalCreate(CreateView):
    model = Festival
    def get(self, request, *args, **kwargs):
        # GET method
        form = FestivalForm()
        context = {"form": form}
        return render(request, "FestivalReservations/festival_form.html", context)

    def post(self, request, *args, **kwargs):
        # POST method
        form = FestivalForm(request.POST)

        FestivalID = form.save()
        FestivalID = FestivalID.pk

        number_of_stages = request.POST['NumberOfStages']

        number_of_stages = int(number_of_stages)
        print(number_of_stages)

        if form.is_valid():
            i = 1
            while i <= number_of_stages:
                new_stage = Stage(Label=i, Festival=Festival.objects.filter(id=FestivalID).first())
                new_stage.save()
                i += 1

            form.save()

        context = {"form": form}
        return render(request, "FestivalReservations/festival_form.html", context)


@method_decorator(allowed_users(allowed_roles=['admin', 'organizer']), name='dispatch')
class FestivalDelete(DeleteView):
    template_name = 'FestivalReservations/festival_delete.html'
    model = Festival
    success_url = "/fest/"

    def post(self, request, pk=None, *args, **kwargs):
        # POST method
        context = {}
        obj = Festival.objects.get(pk=pk)
        if obj is not None:
            obj.delete()
            context['object'] = None
            return redirect('../FestivalList/FestivalBrand')
        return render(request, "FestivalReservations/", context)


class Data():
    def __init__(self, Interpret, Datum, Start, End):
        self.Interpret = Interpret
        self.Datum = Datum
        self.Start = Start
        self.End = End

    Interpret = ""
    Datum = ""
    Start = ""
    End = ""


class FestivalDetail(DetailView):
    model = Festival
    template_name='FestivalReservations/festival_detail.html'

    def get(self, request, *args, **kwargs):
        FestivalID = kwargs.pop("pk")
        festival = Festival.objects.filter(id = FestivalID).first()
        stages = Stage.objects.filter(Festival=FestivalID)

        shows_list = []
        interprets = []
        dates = []
        start_end = {}


        stage_view = dict()
        for stage in stages:
            shows = Show.objects.filter(Stage=stage)            
            if shows:
                stage_view[stage.Label] = list()
                for show in shows:
                    interpret = Interpret.objects.get(show=show)    
                    date = show.Date
                    start = show.Start
                    end = show.End
                    stage_view[stage.Label].append(Data(Interpret = interpret.Name, Datum = date, Start = start, End = end))

        context = {
            "FestivalID" : FestivalID,
            "Stages" : stages,
            "Interprets" : interprets,
            "Dates" : dates,
            "Start_End" : start_end,
            "festival" : festival,
            "stage_view" : stage_view

        }

        return render(request, "FestivalReservations/festival_detail.html", context)


@method_decorator(allowed_users(allowed_roles=['admin', 'organizer']), name='dispatch')
class AddShow(CreateView):
    model = Show
    template_name = 'FestivalReservations/add_show.html'
    success_url = "/fest/"

    def get(self, request, *args, **kwargs):
        # GET method
        FestivalID = kwargs.pop("pk")
        form = ShowForm(FestivalID)

        
        context = {
            "form": form,
            "FestivalID" : FestivalID
            }
        return render(request, "FestivalReservations/add_show.html", context)

    def post(self, request, *args, **kwargs):
        # POST method
        FestivalID = kwargs.pop("pk")

        form = ShowForm(FestivalID, request.POST)

        if form.is_valid():
            stages = Stage.objects.filter(Festival=FestivalID)
            for s in stages:
                if s.id == form.cleaned_data["Stage"].id:
                    stage = s
            show = Show(Start=form.cleaned_data['Start'], End=form.cleaned_data['End'], Date=form.cleaned_data['Date'],
                    Interpret=form.cleaned_data['Interpret'], Stage=stage)
            show.save()

            form = ShowForm(FestivalID)

        context = {
            "form": form,
            "FestivalID" : FestivalID
            }
        return render(request, "FestivalReservations/add_show.html", context)




@method_decorator(allowed_users(allowed_roles=['admin', 'organizer']), name='dispatch')
class FestivalUpdate(UpdateView):
    model = Festival
    fields = ["FestivalBrand", "Place", "Genre", "Start", "End", "PriceForTicket", "Capacity",]
    template_name = 'FestivalReservations/festival_update.html'
    success_url = "/fest/FestivalList"


class InterpretList(ListView):
    model = Interpret

@method_decorator(allowed_users(allowed_roles=['admin', 'organizer']), name='dispatch')
class InterpretCreate(CreateView):
    model = Interpret
    def get(self, request, *args, **kwargs):
        # GET method
        form = InterpretForm()
        context = {"form": form}
        return render(request, "FestivalReservations/interpret_form.html", context)

    def post(self, request, *args, **kwargs):
        # POST method
        form = InterpretForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form = InterpretForm()
        context = {"form": form}
        return render(request, "FestivalReservations/interpret_form.html", context)

@method_decorator(allowed_users(allowed_roles=['admin', 'organizer']), name='dispatch')
class InterpretDelete(DeleteView):
    template_name = 'FestivalReservations/interpret_delete.html'
    model = Interpret
    success_url = "/fest/InterpretList"

    def post(self, request, pk=None, *args, **kwargs):
        # POST method
        context = {}
        obj = Interpret.objects.get(pk=pk)
        if obj is not None:
            obj.delete()
            context['object'] = None
            return redirect('../InterpretList')
        return render(request, "FestivalReservations/", context)

@method_decorator(allowed_users(allowed_roles=['admin', 'organizer']), name='dispatch')
class InterpretUpdate(UpdateView):
    model = Interpret
   #form_class = FestivalForm
    fields = ["Name", "Members", "photoLogo", "Rating", "Genre"]
    template_name = 'FestivalReservations/interpret_update.html'
    success_url = "/fest/InterpretList"



class InterpretDetail(DetailView):
    model = Interpret



@unauthenticated_user
def registerPage(request, *args, **kwargs):
    if 'email' in kwargs:
        form = CreateUserForm(kwargs.pop('email'))
    else:
        form = CreateUserForm(None)
    if request.method == 'POST':
        form = CreateUserForm(None, request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            group = Group.objects.get(name='customer')
            user.groups.add(group)
            login(request, user)
            return redirect('FestivalReservations:user-page')
        

    context = {'form':form}
    return render(request, 'FestivalReservations/register.html', context)


    # if request.method == 'POST':
    #     form = CreateUserForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    # context = {'form':form}
    # return render(request, 'FestivalReservations/register.html', context)

@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password =request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('FestivalReservations:home')
        else:
            messages.info(request, 'Login nebo heslo je chybné')

    context = {}
    return render(request, 'FestivalReservations/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('FestivalReservations:login')

def userPage(request):
    name = str(request.user)
    email = str(request.user.email)
    reservations = request.user.reservations.all()
    if not reservations:
        reservations = None
    context = {"Reservations": reservations, "Name": name, "Email": email}
    return render(request, 'FestivalReservations/user.html', context)



class ReservationCreate(CreateView):
    model = Reservation
    def get(self, request, *args, **kwargs):
        # GET method
        festival_id = kwargs.pop('pk')
        chosen_festival = Festival.objects.filter(id=festival_id).first()
        capacity = self.countCapacity(festival_id)
        avaiable = capacity > 0

FestivalReservations/templates/FestivalReservations/ReservationEdit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<h2>{{festival}}</h2>
	<div class="content">
        <div class="column">
            <form action="{% url 'FestivalReservations:ReservationEdit' res %}" method='POST'> {% csrf_token %}
                {{form.as_p}}
                <input class="save_button" type='submit' value='Uložit úpravy' />
            </form>
        </div>
    </div>
    {%if success == 0%}
    	<p>Změna proběhla úspěšně</p>
    {%endif%}

{% endblock %}

FestivalReservations/templates/FestivalReservations/ReservationsAdmin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	{%for reservation in all_reservations%}
	<div class="res_container">
		<div class="res_info">
			<h2 style="font-size: 1em;">Uživatel: {{reservation.User|default_if_none:"Neregistrovaný"}} | Festival: {{reservation.Festival}} | Počet: {{reservation.Tickets}} ks | Zaplaceno: <input type="checkbox" {% if reservation.Paid %}checked{% endif %} disabled="True" /></h2>

		 <div class="res_settings">
		 	<a href="{% url 'FestivalReservations:ReservationEdit' reservation.id %}"><button class="btn success">Upravit</button></a>
		 	<a href="{% url 'FestivalReservations:ReservationsAdmin' reservation.id %}"><button class="btn danger">X</button></a>
		 </div>
		 	
		</div>
	</div>
	{%endfor%}
	{%if delete%}
	<p>Odstranění proběhlo úspěšně</p>
	{%endif%}
{% endblock %}

FestivalReservations/templates/FestivalReservations/UserAdmin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	{%for user in all_users%}
	<div class="user_container">
			<h2 style="font-size: 1em;">Login: {{user.username}}  Role: {{user.groups.all.0.name}}</h2>
		 	
		 <div class="user_settings">
		 	<a href="{% url 'FestivalReservations:UserEditAdmin' user.id %}"><button class="btn success">Upravit</button></a>
		 	<a href="{% url 'FestivalReservations:ChangePasswordAdmin' user.id %}"><button class="btn success">Změnit heslo</button></a>
		 	<a href="{% url 'FestivalReservations:UserAdmin' user.id %}"><button class="btn danger">X</button></a>
		 </div>
	</div>
	
	{%endfor%}	
	<form action="{% url 'FestivalReservations:AddUser' %}"  method='GET'>
	<button type='submit'>Nový uživatel</button>
	</form>
	{%if delete%}
	<p>Uživatel byl smazán</p>
	{%endif%}
{% endblock %}

FestivalReservations/templates/FestivalReservations/UserEdit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	
	<div class="content">
        <div class="column">
            <form action="{% url 'FestivalReservations:UserEdit' %}" method='POST'> {% csrf_token %}
                {{form.as_p}}
                <input class="save_button" type='submit' value='Uložit změny' />
            </form>
        </div>
        
        {%if success == 0%}
        <p>Změny uloženy.</p>
        {%elif success == -1%}
        <p>Vyskytla se chyba</p>
        {%endif%}
    </div>
	
{% endblock %}

FestivalReservations/templates/FestivalReservations/add_show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="content">
	<div class="column">
		<form action="{% url 'FestivalReservations:AddShow' FestivalID %}" method='POST'> {% csrf_token %}
    		{{form.as_p}}
    		<input class="save_button" type='submit' value='Přidat' />
		</form>
	</div>
</div>

{% endblock %}

FestivalReservations/templates/FestivalReservations/festival_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="content">
	<div class="column">
		<form enctype="multipart/form-data" action="." method="POST"> {% csrf_token %}
    		<p>
                <label for="id_FestivalBrand">Jméno festivalu:</label>
                <input type="text" name="FestivalBrand" placeholder="Your FestBrand!" required="" id="id_FestivalBrand">
            </p>
            <p>
                <label for="id_Place">Místo:</label>
                <input type="text" name="Place" placeholder="Your location" class="" id="" rows="3" cols="50" required="">
            </p>
            <p>
                <label for="id_Genre">Žánr:</label>
                <input type="text" name="Genre" maxlength="30" required="" id="id_Genre">
            </p>
            <p>
                <label for="id_Start">Začátek:</label>
                <input type="date" name="Start" class="form-control" required="" id="id_Start">
            </p>
            <p>
                <label for="id_End">Konec:</label>
                <input type="date" name="End" class="form-control" required="" id="id_End">
            </p>
            <p>
                <label for="id_PriceForTicket">Cena za listek:</label>
                <input type="number" name="PriceForTicket" value="199" required="" id="id_PriceForTicket">
            </p>
            <p>
                <label for="id_Capacity">Kapacita:</label>
                <input type="number" name="Capacity" value="6" required="" id="id_Capacity">
            </p>
            <p>
                <label for="id_NumberOfStages">Počet pódií:</label>
                <input type="number" name="NumberOfStages" required="" id="id_NumberOfStages">
            </p>
            <p>
                <label for="id_photoLogo">Fotka:</label>
                <input type="file" name="photoLogo" accept="image/*" id="id_photoLogo">
            </p>
    		<input class="save_button" type="submit" value="Save">
	</div>
</div>




{% endblock %}

FestivalReservations/templates/FestivalReservations/festival_list.html
{% extends 'base.html' %}
    {% block content %}
    <div class="custom-select">
       <!--  <form action="{% url 'FestivalReservations:FestivalList' %}"> -->
        <p style="float: left; margin-top: 5px;">Seřadit: </p>
            <select id="selectbox" name="" onchange="javascript:location.href = this.value;"> 
                {% if request.path == "/fest/FestivalList/FestivalBrand" %}
                    <option value="FestivalBrand" selected>Název festivalu</option>
                {% else %}
                    <option value="FestivalBrand">Název festivalu</option>
                {% endif %}
                {% if request.path == "/fest/FestivalList/PriceForTicket" %}
                    <option value="PriceForTicket" selected>Cena za lístek</option>
                {% else %}
                    <option value="PriceForTicket">Cena za lístek</option>
                {% endif %}

                {% if request.path == "/fest/FestivalList/Capacity" %}
                    <option value="Capacity" selected>Kapacita</option>
                {% else %}
                    <option value="Capacity">Kapacita</option>
                {% endif %}
            </select>
    </div>
    {% if request.path == "/fest/FestivalList/FestivalBrand" %}
        {%for Fest in festival_list|dictsort:"FestivalBrand" %}
            <div class="fest_container">
                <h2>{{Fest}}</h2>
                <div class="fest_settings">
                    {% if request.user.groups.all.0.name == "admin" or request.user.groups.all.0.name == "organizer"%}
                    <a href="{% url 'FestivalReservations:FestivalUpdate' Fest.id %}"><button class="btn success">Upravit</button></a>
                    <a href="{% url 'FestivalReservations:FestivalDelete' Fest.id %}"><button class="btn danger">Smazat</button></a>
                    <a href="{% url 'FestivalReservations:AddShow' Fest.id %}"><button class="btn success">Přidat vystoupení</button></a>
                    {% endif %}
                    <a href="{% url 'FestivalReservations:FestivalDetail' Fest.id %}"><button class="btn info">Detail</button></a>
                    <a href="{% url 'FestivalReservations:reservation-page' Fest.id %}"><button class="btn info">Reservovat</button></a>
                </div>
            </div>
        {%endfor%}
    {% elif request.path == "/fest/FestivalList/PriceForTicket" %}
        {%for Fest in festival_list|dictsort:"PriceForTicket" %}
            <div class="fest_container">
                <h2>{{Fest}}</h2>
                 <div class="fest_settings">
                    {% if request.user.groups.all.0.name == "admin" or request.user.groups.all.0.name == "organizer"%}
                   <a href="{% url 'FestivalReservations:FestivalUpdate' Fest.id %}"><button class="btn success">Upravit</button></a>
                    <a href="{% url 'FestivalReservations:FestivalDelete' Fest.id %}"><button class="btn danger">Smazat</button></a>
                    <a href="{% url 'FestivalReservations:AddShow' Fest.id %}"><button class="btn success">Přidat vystoupení</button></a>
                    {% endif %}
                    <a href="{% url 'FestivalReservations:FestivalDetail' Fest.id %}"><button class="btn info">Detail</button></a>
                    <a href="{% url 'FestivalReservations:reservation-page' Fest.id %}"><button class="btn info">Reservovat</button></a>
                </div>
            </div>
        {%endfor%}
    {% elif request.path == "/fest/FestivalList/Capacity" %}
        {%for Fest in festival_list|dictsort:"Capacity" %}
            <div class="fest_container">
                <h2>{{Fest}}</h2>
                 <div class="fest_settings">
                    {% if request.user.groups.all.0.name == "admin" or request.user.groups.all.0.name == "organizer"%}
                    <a href="{% url 'FestivalReservations:FestivalUpdate' Fest.id %}"><button class="btn success">Upravit</button></a>
                    <a href="{% url 'FestivalReservations:FestivalDelete' Fest.id %}"><button class="btn danger">Smazat</button></a>
                    <a href="{% url 'FestivalReservations:AddShow' Fest.id %}"><button class="btn success">Přidat vystoupení</button></a>
                    {% endif %}
                    <a href="{% url 'FestivalReservations:FestivalDetail' Fest.id %}"><button class="btn info">Detail</button></a>
                    <a href="{% url 'FestivalReservations:reservation-page' Fest.id %}"><button class="btn info">Reservovat</button></a>
                </div>
            </div>
        {%endfor%}
    {% elif request.path == "/fest/FestivalList/" %}
        {%for Fest in festival_list %}
            <div class="fest_container">
                <h2>{{Fest}}</h2>
                <div class="fest_settings">
                    {% if request.user.groups.all.0.name == "admin" or request.user.groups.all.0.name == "organizer"%}
                    <a href="{% url 'FestivalReservations:FestivalUpdate' Fest.id %}"><button class="btn success">Upravit</button></a>
                    <a href="{% url 'FestivalReservations:FestivalDelete' Fest.id %}"><button class="btn danger">Smazat</button></a>
                    <a href="{% url 'FestivalReservations:AddShow' Fest.id %}"><button class="btn success">Přidat vystoupení</button></a>
                    {% endif %}
                    <a href="{% url 'FestivalReservations:FestivalDetail' Fest.id %}"><button class="btn info">Detail</button></a>
                    <a href="{% url 'FestivalReservations:reservation-page' Fest.id %}"><button class="btn info">Reservovat</button></a>
                </div>
            </div>
        {%endfor%}
    {% endif %}
            
    {% endblock %}

FestivalReservations/templates/FestivalReservations/festival_update.html
{% extends 'base.html' %}
{% block content %}
<div class="content">
	<div class="column">
<h1>Upravit: {{object.FestivalBrand }}</h1>

<form method='POST'>{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Uložit' />
</form>

</div>
</div>

{% endblock %}

FestivalReservations/templates/FestivalReservations/home.html
{% extends 'base.html' %}
{% load static %}

{% block content%}
<div class="container">
	<img id="festival1">
	<div class="heading">
		<h1><a href="{% url 'festivals' %}">Zažij festival.</a></h1>
	</div>
</div>

<script>
    var imgArray = [
        "{% static 'css/festival1.jpeg' %}",
        "{% static 'css/festival2.jpeg' %}",
        "{% static 'css/festival3.jpg' %}"],
        curIndex = 0;
        imgDuration = 2500;

    function slideShow() {
        document.getElementById('festival1').src = imgArray[curIndex];
        curIndex++;
        if (curIndex == imgArray.length) { curIndex = 0; }
        setTimeout("slideShow()", imgDuration);
    }
    slideShow();
</script>
{% endblock %}

FestivalReservations/templates/FestivalReservations/interpret_delete.html
{% extends 'base.html' %}
{% block content %}

<form action="{% url 'FestivalReservations:InterpretDelete' object.id  %}" method='POST'>{% csrf_token %}
    <h1>Urcite chcete odstranit interpreta "{{ object.Name }}"?</h1>
    <p><input type='submit' value='Ano'/>  <a href="{% url 'FestivalReservations:InterpretList' %}">Zrušit</a></p>

</form>

{% endblock %}

FestivalReservations/templates/FestivalReservations/interpret_form.html
{% extends 'base.html' %}
{% block content %}

<div class="content">
    <div class="column">
<form enctype="multipart/form-data" action='.' method='POST'> {% csrf_token %}
    {{form.as_p}}
    <input class="save_button" type='submit' value='Přidat' />
</form>
</div>
</div>


{% endblock %}

FestivalReservations/templates/FestivalReservations/reservation_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h2>{{festival}}</h2>
    {% if capacity %}
        {% if request.user.is_authenticated %}
            <div class="content">
                <div class="column">
                    <form action="{% url 'FestivalReservations:reservation-page' fest %}" method='POST'> {% csrf_token %}
                        {{form.as_p}}
                        <input class="save_button" name="reserve" type='submit' value='Rezervovat' />
                    </form>
                </div>
            </div>
        {% else %}
            <div class="content">
                <div class="column">
                    <form action="{% url 'FestivalReservations:reservation-page' fest %}" method='POST'> {% csrf_token %}
                        {{form.as_p}}
                        <input class="save_button" name="reserve" type='submit' value='Rezervovat' />
                        <input class="save_button" name="reserve_and_register" type='submit' value='Rezervovat a registrovat' />
                    </form>
                </div>
            </div>
        {% endif %}

    {% else %}
        <div class="content">
            <p>Vše vyprodáno</p>
        </div>
    {% endif %}
    {% if success == 0%}
    <p>Rezervace proběhla úspěšně</p>
    {%endif%}
{% endblock %}